### ISSUE TITLE
Would it be possible to accept a flag to reverse the order of the stack

### ISSUE THREAD

**Issue by seanpdoyle** [ko1/pretty_backtrace#1]
I'm in favor of having the stack reversed, so the line you care about is at the bottom (and therefore, at the end of your terminal buffer)

https://storify.com/BVitale/stack-traces-in-reverse-order (Gary Bernhardt's position)

What would it take to pull that off? Would it be as simple as `shift`ing instead of `unshift` ing (or vice versa) stack lines onto a queue that is then joined?

**Comment by ko1** [comment]
Please try and give me a patch.
I think it is difficult because of current MRI's limitation. But not sure.

**Comment by ko1** [comment]
if it is possible, I'm welcome to add an option to choose order.
