### ISSUE TITLE
wrong local variable name `#$!' for #<Binding:0x007fde0acae3e8>

### ISSUE THREAD

**Issue by sardaukar** [ko1/pretty_backtrace#4]
I'm getting this cryptic error when enabling PrettyBacktrace. Is this a Ruby 2.2 issue?

**Comment by jhoffner** [comment]
I get this issue as well, also on Ruby MRI 2.2

**Comment by nina-saule** [comment]
It is working fine on `ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]` for me.

**Comment by ko1** [comment]
Please try v0.1.2.

Reproducible code and full error message (NameError, in this time) are highly recommended for a bug report because I'm not a wizard.

**Comment by sardaukar** [comment]
Well, apparently you are, because _even without reproducible code_, it's fixed in 0.1.2 :D

**Comment by romenigld** [comment]
I'm getting this error and my version of ruby is:
ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

**Comment by ko1** [comment]
See https://github.com/ko1/pretty_backtrace/issues/4#issuecomment-74191690

**Comment by romenigld** [comment]
Hello ko1, I'm trying to do a Contact_form with this tutorial: http://www.murdo.ch/posts/build-a-contact-form-with-rails-4-2
And I'm not using this  PrettyBacktrace, when I see in my lib folder don't have this files! What i need to do?

**Comment by ko1** [comment]
Sorry no idea.

**Comment by romenigld** [comment]
That's ok, thank's ko1!

**Comment by romenigld** [comment]
Just for post what I fixed for this error: My ContactsController don't have the plural name, then I put the ('s) in the final and  was possible to run. I really don't understand why the generator do that automatically.
